services:
  app_bazar:
    build: . #/bazar was deleted to change the ubication of docker-compose to bazar
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://dpg-cs2khve8ii6s739kfru0-a:5432/dbgeneralstore?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: dbgeneralstore_user
      DB_PASSWORD: NznGqQhBEc2cNJIQscKbAfAmI4qCL6XR
    restart: always
#    depends_on:
#      bazar_mysql_image:
#        condition: service_healthy
  dpg-cs2khve8ii6s739kfru0-a:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbgeneralstore
      POSTGRES_USER: dbgeneralstore_user
      POSTGRES_PASSWORD: NznGqQhBEc2cNJIQscKbAfAmI4qCL6XR
 #     MYSQL_ROOT_PASSWORD: 1234
 #     MYSQL_PASSWORD: 1234
 #     MYSQL_DATABASE: generalstoredb
    restart: always
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "bazar_mysql_image" ]
#      timeout: 10s
#      retries: 10
