services:
  app_bazar:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://bazar_mysql_image:3306/generalstoredb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      bazar_mysql_image:
        condition: service_healthy
  bazar_mysql_image:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: generalstoredb
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "bazar_mysql_image" ]
      timeout: 10s
      retries: 10
